apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-main
  namespace: app
  labels:
    app: products-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-main
  template:
    metadata:
      labels:
        app: products-main
    spec:
      containers:
      - name: products
        image: $DOCKER_IMAGES
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "8080"
          - name: HOST_products
            value: http://10.0.14.63:80
          - name: HOST_REVIEWS
            value: http://10.0.0.125:80
      - name: mongo
        image: mongo:4.4.3-bionic
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data"
            name: products-develop
      volumes:
        - name: products-develop
          persistentVolumeClaim:
            claimName: products-develop