apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-develop
  namespace: app
  labels:
    app: products-develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-develop
  template:
    metadata:
      labels:
        app: products-develop
    spec:
      containers:
      - name: products
        image: $DOCKER_IMAGES
        ports:
        - containerPort: 8080
        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "8080"
          - name: HOST_products
            value: http://10.0.3.134:80
          - name: HOST_REVIEWS
            value: http://10.0.10.218:80
      - name: mongo
        image: mongo:4.4.3-bionic
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: "/data"
            name: products-develop
      volumes:
        - name: products-develop
          persistentVolumeClaim:
            claimName: products-develop