version: "3.8"

services:
  products:
    container_name: productsapi_devcontainer
    image: 'productsapi'
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "80:80"
    networks:
      - products_network
    mem_limit: 500m
    restart: 'unless-stopped'

  products_mongo:
    container_name: productsapi_devcontainer
    image: 'mongo'
    #ports:
    #  - "27017:27017"
    networks:
      products_network:
        aliases:
          - mongoproducts
    volumes:
      - 'productsapi_devcontainer_mongodb-data/_data'
    mem_limit: 1000m
    restart: 'unless-stopped'

networks:
  products_network: null

volumes:
  productsapi_devcontainer_mongodb-data: null